### ISSUE TITLE
example

### ISSUE THREAD

**Issue by cnc4less** [Groguard/ILI9341-Arduino-Teensy-MenuSystem#1]
will you kindly provide an example code.

**Comment by Groguard** [comment]
I meant to add an example. Give me a couple days and I will add some.

**Comment by cnc4less** [comment]
i am trying to test it also with stm32-arduino 
http://www.stm32duino.com/viewtopic.php?f=9&t=1856&p=24629&hilit=menu+system#p24629
as others still gives errors and would love to see yours working on stm32-arduino too

**Comment by Groguard** [comment]
I added an example. You may need to modify the library to work with whatever ili9341 library you are using. Thats the only thing that should need to be changed.
